paths:
  /cats:
    get:
      tags:
        - "ApiEndpoint(Cat)"
      description: List all cats
      summary: List cats
      operationId: "listCats"
      responses:
        200:
          description: List of cats retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "ModelRef({/namespaces/mock/versioned/v4/modules/config/released/models/Cat})"
        x-api-responses:
          responseModelName: "ListCatsApiResponse"
        x-codegen-hint:
          $any:
            - type: entity-identifier
              properties:
                identifiers:
                  - type: "ModelRef({/namespaces/mock/versioned/v4/modules/config/released/models/Cat})"
                    container: "array"
                    index: 2001
